states:
  - observation.state.arm.position:
      origin_keys:
        - observation.state:
            start: 0
            end: 7
  - observation.state.hand.position:
      origin_keys:
        - observation.state:
            start: 7
            end: 13

actions:
  - action.arm.position:
      convert_from_state: true
      subtract_state: false
  - action.hand.position:
      convert_from_state: true
      subtract_state: false

images:
  - observation.images.camera_top:
      origin_keys: observation.images.ego_view

norm_stats: assets/norm_stats/cylinder_left_joint_8_18_8_19.json
